### ISSUE TITLE
growable sequence streams

### ISSUE THREAD

**Issue by blaenk** [carllerche/eventual#30]
I have no idea what to call this. But basically I would like the ability to create a sequence stream, by that I mean the specific functionality provided by `sequence` which is to provide a Stream that yields results in the order that they are completed, but be able to continue to 'push' onto that stream. So on one end I want to be able to keep pushing jobs onto the stream, and on the other I want to keep pulling results out in the order that they are finished. Well I don't really care much about order, but my point is that if I push A and then B onto this stream, but B finishes first, I don't want an await() on the stream to block until A finishes since I pushed A first, I want to get B's result.

**Comment by blaenk** [comment]
Actually, what's the difference between the `collect` method on `Stream` and what `sequence` does? Given my goals they both seem similar. Perhaps I can work with collect though since it yields a future, then perhaps I can join these together. My concern is that as I nest and nest futures this way, I worry that I'll no longer have the effect that I want. I just want to push jobs/futures onto a stream/pool/whatever and then get results as they come in, but continue to be able to push jobs.

**Comment by blaenk** [comment]
Sorry for the spam. But yeah I misread what `collect` was saying, it says "returning them sorted by order of arrival", but that's arrival to the stream, not arrival from having been completed. I'll have to give this some more thought.

**Comment by reem** [comment]
cc me, I am also very interested in this functionality.

**Comment by reem** [comment]
@blaenk how similar are your needs to #8? It seems like you want some specific ordering guarantees, but at a high level..

**Comment by blaenk** [comment]
I'm honestly not very sure what #8 means. I basically want what `sequence` appears to give you, which is that given a collection of futures, produce a Stream that, when you `await()` on it, it gives you any existing result (or waits for one) regardless of the order that the future producing that result was in the collection of futures given to `sequence`.

The problem for me is that once you `sequence` a collection of futures, that's it, you can't add more futures after the fact, as far as I can tell. So it's not so much that I care about a specific order, just in general I want to get results as they become available. I'm having a hard time articulating this, perhaps that's not even what you were asking about, or you already understood that part.

To reiterate and perhaps put it more simply, I want to fire off a bunch of futures (deferred/pooled, but that's besides the point) and then process the results as they become available, **_without**_
1. waiting _until_ they're all available (rules out `join` afaik)
2. waiting for earlier futures to complete even though later futures have already produced a result.

```
let futures = vec![future1, future2, future3];
let stream = sequence(futures);

// let's say that future2 is done, this yields its result
// even though future1 and future3 are still incomplete
let result2 = stream.await();

// now I would like to 'push' more futures onto the stream
// which will participate in the same behavior
stream.push(future4);
```

I think this might be possible if `sequence` returned the `Sender` part of the `Stream`? Not sure.

**Comment by blaenk** [comment]
@reem I think I see what you mean now by referencing #8. So even if we had the `Sender`, sending something consumes the `Sender`, so I would only be able to send one extra Future, I think. It seems like currently we can get the `Sender` back by awaiting on the `send()` call? Not sure.

**Comment by carllerche** [comment]
I think Eventual's biggest problem right now is a lack of documentation :) I am currently focusing on mio documentation and then will hopefully be able to circle back to Eventual.

I wonder if what you want is `Stream::process` ([implementation](https://github.com/carllerche/eventual/blob/master/src/process.rs))

Of course, it is completely undocumented :) Basically, it "maps" a stream w/ up to N "in-flight" operations, and returns a new `Stream` in order of completion.

**Comment by blaenk** [comment]
So by "N in flight operations" does that mean that there can be up to N futures 'processing' at a time? And you provide `process` a callback to run for each result? If so that's cool and does seem useful to me.

However, my main problem (which I filed this issue for) is that I want to be able to continue to add futures to a stream. So say I produce a stream using `Stream::process` right, I'd like to be able to continue to add futures to it.

**Comment by carllerche** [comment]
Process operates on a stream and streams can be unbounded...

However, I will need to think a bit more about this. it could be that this would be best suited by a tweak on the send side, which would be related to #8 but not an exact match.

**Comment by blaenk** [comment]
Yeah I get that they're unbounded but my question is how could you leverage that, it seems I would need access to the stream Sender. The only way I've seen to access that is if you created the stream manually with the pair method. Is that what I would do? Create one that way then map the stream component using something like process which yields another stream, will sending to the original stream's sender pair still work?

**Comment by carllerche** [comment]
Can you describe your use case more? You said 'push' onto that stream, that would require using the `Sender` half...

**Comment by blaenk** [comment]
I think I realize what my misunderstanding was now. At first I was thinking that if I used sequence then there was no way to access the sender half to then go ahead and add more futures. I then figured the same problem existed with process, but if I understand things now, process augments an existing stream like you said, maps it, so that I could create a stream using pair (which AFAIK is the only way to access the sender half) then map the stream using process, and I will _still_ be able to send via the sender half. I imagined that using process would somehow create a new stream while discarding the one being mapped, thereby invalidating the original stream's sender half.

Now I think of it like a stream being connected to and feeding into another stream, if I am correct.

I haven't had a chance to play around with this since I opened the issue, but I'll give that a shot next time I get a chance:
1. (tx, rx) = Stream::pair
2. mapped = Stream::process(rx)
3. tx.send will work as expected, that is, it'll partake in the behavior that 'process' exhibits

(I'm on mobile, sorry for any mistakes)

**Comment by carllerche** [comment]
I believe that is correct. There may turn out to be some features missing on the `Sender` side, but we will see.

**Comment by blaenk** [comment]
So I think I may indeed be running into #8. What I'm experiencing is that a `Sender` send doesn't 'complete' until it's been consumed from the `Stream` end is that correct? I was hoping I could treat it kind of like a channel, just send as much as I want, since like you say it's "unbounded," and then loop while awaiting on results from the `Stream`. But since it _seems_ like a send doesn't complete until it's been consumed on the `Stream` end, I can't get the sender back after sending something until it's been consumed. I'd end up having to use yet another thread just to separate the sending from the consuming. [`test_one_shot_stream_done`](https://github.com/carllerche/eventual/blob/33c8eec8b3b98fb665e0600ebbe98d1c4fc06f6e/test/test_stream_receive.rs#L30) seems to confirm this.

An alternative perhaps would be if I could interleave sending and consuming, but I don't think that'd work out in my case. I wanted to do something like consume from the stream, where sometimes a consumed result would have the effect of pushing many more items to the stream, if that makes any sense.

It's also pretty tedious that the sender consumes itself. Mainly because if I want to send many things I end up just doing something like `sender = sender.and_then(|s| s.send(other_thing))`, but that means the type of `sender` here has to be `Future<Sender<T, E>, ()>`, so for that _first_ send, this wouldn't work because `sender` would actually be a `Sender<T, E>`, I've worked around this by turning the `Sender` into a `Future` right away by doing something like `sender.and_then(|s| s)`, which yields `Future<Sender<T, E>, ()>`.

So I _think_ #8 would help because if I understand it correctly, it would both 1) allow me to send things without consuming `self`, and 2) allow me to send many things using some sort of `Buffer`, would that then allow me to just 'fire and forget' send without having to wait until the sent item is consumed on the other end before I can continue sending things?

**Comment by blaenk** [comment]
Oh and I'm pretty sure I can turn the sender into a future more easily by just using `Future::of`.

**Comment by carllerche** [comment]
Thanks for the report. I'm going to close this as the crate is deprecated in favor of [futures](https://crates.io/crates/futures).
