### ISSUE TITLE
pooled streams

### ISSUE THREAD

**Issue by blaenk** [carllerche/eventual#31]
So now that we have `defer` and `background` I'm wondering if we can extend them to work with `Stream`. They both take a `Future`. I see that you can convert a `Stream` to a `Future` but it seems unwieldy since it's a future that would yield a pair of the evaluated head and the rest of the stream, so you'd have to keep pushing it back into a defer?

It'd be nice if there were a higher-level way of simply stating that a given stream should be processed given a certain threadpool, so you just continue using it as usual.

**Comment by reem** [comment]
I also have a need for this, I'll take a crack at it when I get the chance.

**Comment by carllerche** [comment]
Thanks for the report. I'm going to close this as the crate is deprecated in favor of [futures](https://crates.io/crates/futures).
