### ISSUE TITLE
Encapsulate syncbox dependency by re-exporting it as a public module under eventual

### ISSUE THREAD

**Issue by jnicholls** [carllerche/eventual#38]
To avoid dependency versioning mismatch, and ease the use of eventual for the defer/background functions (by eliminating the need for a consumer to have a direct dependency on syncbox in addition to eventual), I would suggest re-exporting syncbox symbols as if they were owned by eventual.

I don't use eventual for this purpose, but I saw this in the code and thought I'd add a ticket here so it's tracked.

**Comment by carllerche** [comment]
:+1:

**Comment by carllerche** [comment]
Thanks for the report. I'm going to close this as the crate is deprecated in favor of [futures](https://crates.io/crates/futures).
