### ISSUE TITLE
Is eventual composable with libraries like mio or mioco? 

### ISSUE THREAD

**Issue by brendanzab** [carllerche/eventual#44]
It would be super nice to have futures and streams for [mio](https://github.com/carllerche/mio) or [mioco](https://github.com/dpc/mioco), but there is no mention that it is safe to use eventual with them. I've looked through the code, but I'm not sure I understand it well enough to know if it is ok.

In a similar vein, how heavy are the overheads of eventual's abstractions? Are they compatible with mio or mioco's goals of lightweight concurrency?

cc. @dpc.

**Comment by burdges** [comment]
I suppose this could be rephrased as a suggestion that [eventual_io](https://github.com/carllerche/eventual_io) be mentioned in the README.md file.

**Comment by carllerche** [comment]
Thanks for the report. I'm going to close this as the crate is deprecated in favor of [futures](https://crates.io/crates/futures).
