### ISSUE TITLE
Implement Deref on Future

### ISSUE THREAD

**Issue by carllerche** [carllerche/eventual#5]
Moved from syncbox repo: https://github.com/carllerche/syncbox/issues/1

**Comment by reem** [comment]
What would this do?

**Comment by carllerche** [comment]
It would block until the future is completed, then return `&T`. However, because of the implied nature of the blocking, I am unsure if this is the best strategy. Perhaps `Future::get(&self) -> &T` might be better...

**Comment by reem** [comment]
I think adding "silent" blocking would be pretty bad, since a primary use case for Futures is in situations where blocking is rather undesirable - an explicit method would be better.
